package com.example.mymacrosapplication.model

data class Food(
    val allHighlightFields: String,
    val brandName: String,
    val brandOwner: String,
    val dataSource: String,
    val dataType: String,
    val description: String,
    val discontinuedDate: String,
    val fdcId: Int,
    val finalFoodInputFoods: List<Any?>,
    val foodAttributeTypes: List<FoodAttributeType>,
    val foodAttributes: List<FoodAttributeX>,
    val foodCategory: String,
    val foodMeasures: List<Any?>,
    val foodNutrients: List<FoodNutrient>,
    val foodVersionIds: List<Any?>,
    val gpcClassCode: Int,
    val gtinUpc: String,
    val householdServingFullText: String,
    val ingredients: String,
    val marketCountry: String,
    val microbes: List<Any?>,
    val modifiedDate: String,
    val packageWeight: String,
    val preparationStateCode: String,
    val publishedDate: String,
    val score: Double,
    val servingSize: Double,
    val servingSizeUnit: String,
    val shortDescription: String,
    val subbrandName: String,
    val tradeChannels: List<String>
)